import Head from 'next/head'
import MediaLeft from '../components/utills/media.left/media.left'
import Domaines from '../components/utills/domaines/domaines'
import Caroussel from '../components/utills/caroussel'
import Rating from '../components/utills/rating/rating'
import style from '../styles/index.module.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet"/>
      </Head>
      <MediaLeft/>
      <div className="LayoutHorizontal h100 ml50">
         <div className={style.one}> 
                <Caroussel/>
              </div>
              {/* <Rating/>
              <div className={style.domaineContainer}>
                <Domaines
                  src="/images/data.svg"
                  title1="DATA"
                  title2="ANALYSE"
                  style={{
                    color:'#5AAAE7'
                  }}
                />
                <Domaines
                  src="/images/mobile.svg"
                  title1="DEVELOPPEMENT"
                  title2="MOBILE"
                  style={{
                    color:'#F948B4'
                  }}
                />
                <Domaines
                  src="/images/web.svg"
                  title1="DEVELOPPEMENT"
                  title2="WEB"
                  style={{
                    color:'#615DF9'
                  }}
                />
              </div>
              <div></div> */}
      </div>

     
    </>
  )
}
